---
abstract: 'A very simple module to validate national insurance number (UK).'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Module::Build: 0.36
  Readonly: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-NIN
provides:
  Algorithm::NIN:
    file: lib/Algorithm/NIN.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
